---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-database-authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cnpg-database-authentik
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: authentik
        property: AUTHENTIK_POSTGRESQL__USER
    - secretKey: password
      remoteRef:
        key: authentik
        property: AUTHENTIK_POSTGRESQL__PASSWORD
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik
spec:
  cluster:
    name: postgres17
  name: authentik
  owner: authentik
