# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
spec:
  chartRef:
    kind: OCIRepository
    name: democratic-csi
  interval: 1h
  values:
    controller:
      driver:
        image:
          tag: next
    csiDriver:
      name: "org.democratic-csi.nfs"
    storageClasses:
      - &nfs
        name: nfs
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
          detachedVolumesFromSnapshots: "false"
        mountOptions: ["nfsvers=4", "noatime"]
        secrets:
          controller-expand-secret: null
          controller-publish-secret: null
          node-publish-secret: null
          node-stage-secret: null
          provisioner-secret: null
      - <<: *nfs
        name: nfs-retain
        reclaimPolicy: Retain
    volumeSnapshotClasses:
      - name: nfs
        parameters:
          detachedSnapshots: "true"
    driver:
      config:
        driver: freenas-api-nfs
        httpConnection:
          allowInsecure: true
          host: 192.168.210.251
          port: 443
          protocol: https
          apiKey: ""
        instance_id: null
        nfs:
          shareHost: 192.168.255.251
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMapallUser: nfs
          shareMapallGroup: nfs
          shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
        zfs:
          datasetParentName: fast/k8s/nfs/volumes
          detachedSnapshotsDatasetParentName: fast/k8s/nfs/snapshots
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 3003
          datasetPermissionsGroup: 3003
          datasetProperties:
            "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
  valuesFrom:
    - kind: Secret
      name: truenas-api-secret
      valuesKey: apiKey
      targetPath: driver.config.httpConnection.apiKey

