---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./influxdata.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./minecraft.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./xenitab.yaml
