---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: auth-sonarr
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: sonarr
  extAuth:
    failOpen: false
    recomputeRoute: true
    headersToExtAuth:
      - Cookie
      - X-Forwarded-Proto
      - X-Forwarded-Host
      - X-Forwarded-Uri
      - X-Forwarded-For
    http:
      backendRefs:
        - kind: Service
          name: authentik-server
          namespace: default
          port: 80
      path: /outpost.goauthentik.io/auth/envoy
      headersToBackend:
        - Set-Cookie
        - "${AUTH_HEADER:=X-authentik-uid}"
        - X-authentik-username
        - X-authentik-name
        - X-authentik-email
        - X-authentik-groups
        - X-authentik-entitlements

