---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../common/alerts

resources:
  - ./13ft-ladder/ks.yaml
  - ./it-tools/ks.yaml
  - ./openspeedtest/ks.yaml
  - ./readeck/ks.yaml
  - ./namespace.yaml
