---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network

components:
  - ../../common/alerts

resources:
  - ./namespace.yaml
  - ./certificates/ks.yaml
  - ./dns/ks.yaml
  - ./echo/ks.yaml
  - ./envoy-gateway/ks.yaml
