---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spaceengineers
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: spaceengineers
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: TORCH_PASS
      remoteRef:
        key: spaceengineers
        property: TORCH_PASS
    - secretKey: RCON_TOKEN
      remoteRef:
        key: spaceengineers
        property: RCON_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spaceengineers-backups
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: spaceengineers-backups
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: spaceengineers-backups
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: spaceengineers-backups
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: spaceengineers-backups
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: spaceengineers-backups
        property: RESTIC_PASSWORD
