---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spaceengineers
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: spaceengineers
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: TORCH_PASS
      remoteRef:
        key: spaceengineers
        property: TORCH_PASS
    - secretKey: RCON_TOKEN
      remoteRef:
        key: spaceengineers
        property: RCON_TOKEN

