---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spaceengineers
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: spaceengineers
  values:
    controllers:
      game:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          game:
            image:
              repository: ghcr.io/krobertson/space-engineers-torch
              tag: latest@sha256:4e526fc99969e12b9058da5e0e5d32c392230536e7fa1f28a341b56785fd051e
            env:
              # wine doesn't like /games being owned by root
              WINEPREFIX: /games/spaceengineers/.wine
              WINEDLLOVERRIDES: "mscoree=n,b;mshtml=n,b;websocket=n,b"
            ports:
              - containerPort: 27016
                protocol: UDP
                hostPort: 27016
              - containerPort: 8766
                protocol: UDP
                hostPort: 8766

          # Configure the code-server sidecar
          code:
            dependsOn: game
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.109.2-39
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/games/.vscode"
              - --extensions-dir
              - "/games/.vscode"
              - --port
              - "8081"
              - "/games"

          rcon-exporter:
            dependsOn: game
            image:
              repository: ghcr.io/krobertson/space-engineers-exporter
              tag: 1.0.2-1@sha256:0f8dc4ebfe6eecdc0375064b1299ba67508243400c4c893c57d51d096e0e9fb2
            env:
              RCON_HOST: localhost
              RCON_PORT: 8080
            envFrom:
              - secretRef:
                  name: spaceengineers

          torch-exporter:
            dependsOn: game
            image:
              repository: ghcr.io/krobertson/torch-remote-exporter
              tag: dev@sha256:e21358d5160575a317b1f2d805bebd50e104e72fb091315c646d0cf39b4c04b8
            env:
              TORCH_HOST: localhost
              TORCH_PORT: 8787
            envFrom:
              - secretRef:
                  name: spaceengineers

          log-cleanup:
            image:
              repository: ghcr.io/krobertson/cleanup-older-files
              tag: dev@sha256:a2c4e3b5dcbc453f9c02d955abc85a5bb1a6246fda649895f52ffafb329df794
            env:
              LOGS_DIRECTORIES: /games/spaceengineers/instance /games/spaceengineers/Logs
              LOG_FILE_ENDINGS: log txt
              DAYS_OLD: "3"

          logrotate:
            image:
              repository: ghcr.io/lazybytez/logrotate-container
              tag: 2.0.0@sha256:6b502467fd4f14c6542784c474b830d64e2ff85eea9e91728d28fb88289f5298
            env:
              LOGS_DIRECTORIES: /games/spaceengineers/instance /games/spaceengineers/Logs
              LOG_FILE_ENDINGS: log txt
              LOGROTATE_INTERVAL: daily
              LOGROTATE_SIZE: 100M
              LOGROTATE_AUTOUPDATE: "true"
            securityContext:
              runAsUser: 0
              runAsGroup: 0

    service:
      code:
        ports:
          http:
            port: 8081
      game:
        ports:
          server:
            port: 27016
            protocol: UDP
          steam:
            port: 8766
            protocol: UDP
      rcon-exporter:
        ports:
          http:
            port: 9122
      torch-exporter:
        ports:
          http:
            port: 9090
    route:
      code:
        hostnames:
          - spaceengineers.r7n.dev
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: code
                port: 8081
      game-server:
        kind: UDPRoute
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: spaceengineers-server
        rules:
          - backendRefs:
            - identifier: game
              port: 27016
      game-steam:
        kind: UDPRoute
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: spaceengineers-steam
        rules:
          - backendRefs:
            - identifier: game
              port: 8766
    serviceMonitor:
      rcon-exporter:
        endpoints:
          - port: http
        service:
          identifier: rcon-exporter
      torch-exporter:
        endpoints:
          - port: http
        service:
          identifier: torch-exporter
    persistence:
      games:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: openebs-hostpath
        size: 50Gi
        globalMounts:
          - path: /games
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
