---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spaceengineers
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: spaceengineers
  values:
    controllers:
      game:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          game:
            image:
              repository: ghcr.io/krobertson/space-engineers-torch
              tag: latest@sha256:4e526fc99969e12b9058da5e0e5d32c392230536e7fa1f28a341b56785fd051e
            env:
              # wine doesn't like /games being owned by root
              WINEPREFIX: /games/spaceengineers/.wine
              WINEDLLOVERRIDES: "mscoree=n,b;mshtml=n,b;websocket=n,b"
            ports:
              - containerPort: 27016
                protocol: UDP
                hostPort: 27016
              - containerPort: 8766
                protocol: UDP
                hostPort: 8766
              - containerPort: 8080
                protocol: TCP
                hostPort: 8080

          # Configure the code-server sidecar
          code:
            dependsOn: game
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.109.2-39
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/games/.vscode"
              - --extensions-dir
              - "/games/.vscode"
              - --port
              - "8081"
              - "/games"

          exporter:
            dependsOn: game
            image:
              repository: ghcr.io/krobertson/torch-remote-exporter
              tag: dev
            env:
              TORCH_HOST: localhost
              TORCH_PORT: 8080
            envFrom:
              - secretRef:
                  name: spaceengineers

    service:
      code:
        ports:
          http:
            port: 8081
      exporter:
        ports:
          http:
            port: 9090
    route:
      code:
        hostnames:
          - spaceengineers.r7n.dev
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: code
                port: 8081
    serviceMonitor:
      exporter:
        endpoints:
          - port: http
        service:
          identifier: exporter
    persistence:
      games:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: openebs-hostpath
        size: 50Gi
        globalMounts:
          - path: /games
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
