---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spaceengineers
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: spaceengineers
  values:
    controllers:
      game:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        initContainers:
          install-steam:
            image:
              repository: ghcr.io/krobertson/game-containers/steamcmd
              tag: rolling@sha256:a33d9109de3f8eb14b4beb98aa5a36f6049608062fd8e89623ad559521dd1e7f
            env:
              STEAM_APPID: "298740"
              STEAM_WINDOWS_INSTALL: "1"
          install-wine:
            image:
              repository: ghcr.io/krobertson/game-containers/wine
              tag: stable@sha256:597ed8709168a5a131f04e200671e9d4ae2f4632b7cba573dfe614afec0f81a8
            env:
              WINETRICKS: vcrun2022 corefonts dotnet48
            command: [ "setupwine.sh" ]
          install-torch:
            image:
              repository: ghcr.io/krobertson/game-containers/base
              tag: stable@sha256:838019f04bab7fd7e12540b9cb29eba544ca30d52ce1d6f1a9ced94e8d6c489a

        containers:
          server:
            image:
              repository: ghcr.io/krobertson/game-containers/wine
              tag: stable@sha256:597ed8709168a5a131f04e200671e9d4ae2f4632b7cba573dfe614afec0f81a8
            env:
              WINEDLLOVERRIDES: "mscoree=n,b;mshtml=n,b"

          code:
            dependsOn: server
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.109.2-39
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/games/.vscode"
              - --extensions-dir
              - "/games/.vscode"
              - --port
              - "8081"
              - "/game"

    service:
      server:
        ports:
          server:
            port: 27016
            protocol: UDP
          steam:
            port: 8766
            protocol: UDP
      code:
        ports:
          http:
            port: 8081
    route:
      code:
        hostnames:
          - spaceengineers.r7n.dev
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: code
                port: 8081
      server:
        kind: UDPRoute
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: spaceengineers-server
        rules:
          - backendRefs:
            - identifier: server
              port: 27016
      steam:
        kind: UDPRoute
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: spaceengineers-steam
        rules:
          - backendRefs:
            - identifier: server
              port: 8766
    persistence:
      scripts:
        type: configMap
        name: spaceengineers-scripts
        defaultMode: 0755
        advancedMounts:
          game:
            install-torch:
              - path: /usr/local/bin/run.sh
                subPath: install-torch.sh
                readOnly: true
            server:
              - path: /usr/local/bin/run.sh
                subPath: start.sh
                readOnly: true
      game:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: openebs-hostpath
        size: 50Gi
        globalMounts:
          - path: /game
      configs:
        type: configMap
        name: spaceengineers-configs
        defaultMode: 0644
        globalMounts:
          - path: /opt/default
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
