---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./securitypolicy.yaml
configMapGenerator:
  - name: spaceengineers-scripts
    files:
      - install-torch.sh=./scripts/install-torch.sh
      - start.sh=./scripts/start.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
