---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-backups
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: minecraft-backups
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: minecraft-backups
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: minecraft-backups
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: minecraft-backups
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: minecraft-backups
        property: RESTIC_PASSWORD

