---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../common/alerts

resources:
  - ./homepage/ks.yaml
  - ./glance/ks.yaml
  - ./namespace.yaml
