---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: authentik
        property: AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: authentik
        property: AUTHENTIK_POSTGRESQL__USER
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: authentik
        property: AUTHENTIK_POSTGRESQL__PASSWORD
    - secretKey: INIT_POSTGRES_USER
      remoteRef:
        key: authentik
        property: AUTHENTIK_POSTGRESQL__USER
    - secretKey: INIT_POSTGRES_PASS
      remoteRef:
        key: authentik
        property: AUTHENTIK_POSTGRESQL__PASSWORD
    - secretKey: AUTHENTIK_EMAIL__HOST
      remoteRef:
        key: smtp-relay
        property: SMTP_RELAY_SERVER
    - secretKey: AUTHENTIK_EMAIL__USERNAME
      remoteRef:
        key: smtp-relay
        property: SMTP_RELAY_USERNAME
    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        key: smtp-relay
        property: SMTP_RELAY_PASSWORD
    - secretKey: INIT_POSTGRES_SUPER_USER
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_USER
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_PASS
